version: '3.8'

services:
  # Redis 서비스 
  redis:
    image: redis:6.0
    container_name: seurasaeng_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  # 백엔드 서비스
  backend:
    image: seuraseung-backend:latest
    container_name: seurasaeng_backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  # 프론트엔드 서비스
  frontend:
    image: seuraseung-frontend:latest
    container_name: seurasaeng_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped