version: '3.8'

services:
  postgres:
    image: postgres:15.12
    container_name: seurasaeng_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:6.0
    container_name: seurasaeng_redis
    ports:
      - "6379:6379"

  backend:
    image: seuraseung-backend:latest
    container_name: seurasaeng_backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: