networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

services:
  postgres:
    image: postgres:15.12
    container_name: seuraseung-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    networks:
      - backend-network

  redis:
    image: redis:6.0-alpine
    container_name: seuraseung-redis
    restart: unless-stopped
    command: redis-server --databases 2
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - backend-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: seuraseung-backend:latest
    container_name: seuraseung-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_KEY=${JWT_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - backend-network
    depends_on:
      - postgres
      - redis