version: '3.8'

services:
  postgres:
    image: postgres:15.12
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ap-northeast-2
      AWS_BUCKET: profile-qrcode
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 1
      CORS_ALLOWED_ORIGINS: https://seurasaeng.site
      spring.cloud.aws.credentials.access-key: ${AWS_ACCESS_KEY}
      spring.cloud.aws.credentails.secret-key: ${AWS_SECRET_KEY}
      spring.cloud.aws.region.static: ap-northeast-2
      spring.cloud.aws.s3.bucket: profile-qrcode
      MAIL_USERNAME: youjiyeon4@gmail.com
      MAIL_PASSWORD: hmqv wsha xdgs hdie
      JWT_KEY: ${JWT_KEY}
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: