version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_SOCKET_URL: ${VITE_SOCKET_URL}
        VITE_MOBILITY_API_KEY: ${VITE_MOBILITY_API_KEY}
        VITE_KAKAOMAP_API_KEY: ${VITE_KAKAOMAP_API_KEY}
        VITE_PERPLEXITY_API_KEY: ${VITE_PERPLEXITY_API_KEY}
        VITE_MOBILITY_API_BASE_URL: ${VITE_MOBILITY_API_BASE_URL}
        VITE_KAKAOMAP_API_BASE_URL: ${VITE_KAKAOMAP_API_BASE_URL}
    image: seuraseung-frontend:latest
    container_name: seuraseung-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_WORKER_PROCESSES=auto