version: '3.8'

services:
  frontend:
    image: seuraseung-frontend:latest
    container_name: seuraseung-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NGINX_WORKER_PROCESSES=auto