name: Backend Deploy

on:
  push:
    branches: [ dev ]
    paths: 
      - 'seurasaeng_be/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Backend Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BACK_SERVER_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: AWS_ACCESS_KEY,AWS_SECRET_KEY,ENCRYPTION_KEY,JWT_KEY
        script: |
          cd /home/ubuntu
          if [ -d "seurasaeng_be" ]; then
            rm -rf seurasaeng_be
          fi
          git clone https://github.com/${{ github.repository }}.git temp_repo
          mv temp_repo/seurasaeng_be .
          rm -rf temp_repo
          cd seurasaeng_be
          export AWS_ACCESS_KEY="${{ secrets.AWS_ACCESS_KEY }}"
          export AWS_SECRET_KEY="${{ secrets.AWS_SECRET_KEY }}"
          export ENCRYPTION_KEY="${{ secrets.ENCRYPTION_KEY }}"
          export JWT_KEY="${{ secrets.JWT_KEY }}"
          docker-compose down
          docker-compose up -d --build