name: Backend Deploy

on:
  push:
    branches: [ dev ]
    paths: 
      - 'seurasaeng_be/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Backend Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BACK_SERVER_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/seurasaeng_be
          git pull origin main
          cat > .env << EOF
          DB_URL=jdbc:postgresql://postgres:5432/postgres
          DB_USERNAME=postgres
          DB_PASSWORD=postgres
          AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION=ap-northeast-2
          AWS_BUCKET=profile-qrcode
          ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }}
          REDIS_HOST=redis
          REDIS_PORT=6379
          REDIS_DB=1
          CORS_ALLOWED_ORIGINS=https://seurasaeng.site
          spring.cloud.aws.credentials.access-key=${{ secrets.AWS_ACCESS_KEY }}
          spring.cloud.aws.credentails.secret-key=${{ secrets.AWS_SECRET_KEY }}
          spring.cloud.aws.region.static=ap-northeast-2
          spring.cloud.aws.s3.bucket=profile-qrcode
          MAIL_USERNAME=youjiyeon4@gmail.com
          MAIL_PASSWORD=hmqv wsha xdgs hdie
          JWT_KEY=${{ secrets.JWT_KEY }}
          EOF
          docker-compose down
          docker-compose up -d --build