name: Deploy Backend

on:
  push:
    branches: [dev]
    paths: ['seurasaeng_be/**']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: |
        cd seurasaeng_be
        mvn clean package -DskipTests
        
    - name: Build Docker Image
      run: |
        cd seurasaeng_be
        docker buildx build --platform linux/arm64 -t seuraseung-backend:latest . --load
        docker save seuraseung-backend:latest | gzip > seurasaeng_be-image.tar.gz
        
    - name: Copy to Server
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.FRONT_SERVER_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "seurasaeng_be-image.tar.gz,seurasaeng_be/"
        target: "/home/ubuntu/"
        
    - name: Deploy Backend
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.FRONT_SERVER_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # 백엔드 서버로 전송
          scp -i ~/.ssh/susumon.pem -o StrictHostKeyChecking=no /home/ubuntu/seurasaeng_be-image.tar.gz ubuntu@10.0.2.166:/home/ubuntu/
          scp -i ~/.ssh/susumon.pem -o StrictHostKeyChecking=no -r /home/ubuntu/seurasaeng_be/ ubuntu@10.0.2.166:/home/ubuntu/
          
          # 백엔드 서버에서 배포
          ssh -i ~/.ssh/susumon.pem -o StrictHostKeyChecking=no ubuntu@10.0.2.166 '
            cd /home/ubuntu/seurasaeng_be
            docker load < ../seurasaeng_be-image.tar.gz
            docker-compose down
            docker-compose up -d
            
            echo "⏳ 백엔드 시작 대기..."
            for i in {1..20}; do
              sleep 5
              if curl -f http://localhost:8080 >/dev/null 2>&1; then
                echo "✅ 백엔드 배포 성공!"
                exit 0
              fi
            done
            echo "❌ 백엔드 배포 실패"
            docker-compose logs backend
            exit 1
          '